---
title: "Predictors_of_PISA_Scores"
author: "Edoardo Ruvolo and Sami Louahlia"
format: html
---

```{r}
here::i_am("Data_Project_M1_Edoardo_Sami.Rproj")
library(here)
library(ggplot2)
library(dplyr)
library(vroom)
library(tidyr)
```

### Data Loading 
Data files are small yet numerous, fortunately, there are only so many ways organizations can name countries so joining the files is not too challenging.

## UNESCO Data
```{r}
Survival_Rate <- vroom(here("Data_UNESCO_21_11/Survival_Rate.csv"))
Share_Studs_Priv <- vroom(here("Data_UNESCO_21_11/Share_Priv_lowsec.csv"))
Enrolment <- vroom(here("Data_UNESCO_21_11/Tot_Enrol_Rate_Lowsec.csv"))

Start_Yr <- vroom(here("Data_UNESCO_21_11/Start_Month_Acad.csv"))
End_Yr <- vroom(here("Data_UNESCO_21_11/End_Month_Acad.csv"))

Gov_Exp <- vroom(here("Data_UNESCO_21_11/Gov_Exp_GDP.csv"))

MeanSchooling <- vroom(here("Data_UNESCO_21_11/Mean_Yrs_Schooling.csv"))
EntranceAge <- vroom(here("Data_UNESCO_21_11/Entrance_Age.csv"))

```

## World Bank Data

```{r}
Pop_Density <- vroom(here("WB_Data/Reworked_Density.csv"))
Fertility_Rate <- read.csv(here("WB_Data/Population Fertility.csv"), col.names =c("Country Code","Indicator Name","Indicator Code", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970","1971","1972","1973","1974","1975","1976","1977","1978","1979","1980","1981","1982","1983","1984","1985","1986","1987","1988","1989","1990","1991","1992","1993","1994","1995","1996","1997","1998","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010","2011","2012","2013","2014","2015","2016","2017","2018","2019","2020","2021","2022","Country_Name"),skip = 4)

```
The method is not great I admit but R was unable to understand the variables on its own.I commited a crime but this was the only way out. I will find a solution later on.

